### ISSUE TITLE
Error connecting to shadow-cljs repl: `(void-function :number)`

### ISSUE THREAD

**Issue by LucianoLaratelli** [doomemacs/doomemacs#5561]
### What did you expect to happen?

I expected to be able to launch `cider-jack-in-cljs` in a Clojurescript buffer and have it connect to a shadow-cljs repl.

### What actually happened?

When the `Select ClojureScript REPL type:` prompt shows up after nrepl launches, I see a "Basic face for shadowed text" column (which started happening when this bug did) 
![Screen Shot 2021-10-02 at 3 47 20 PM](https://user-images.githubusercontent.com/7403854/135730005-3be2a00d-a302-4684-a247-bfad9e0b4ea6.png)

If I select Shadow, a `error in process filter: Symbol’s function definition is void: :number` message is logged in the minibuffer. If I go to `*Messages*`, I see these lines logged:
```
[nREPL] Starting server via /opt/homebrew/bin/npx shadow-cljs -d nrepl/nrepl:0.9.0-beta2 -d cider/piggieback:0.5.2 -d refactor-nrepl/refactor-nrepl:2.5.1 -d cider/cider-nrepl:0.26.0 server
[nREPL] server started on 57539
error in process filter: parseclj-lex--leaf-token-value: Symbol’s function definition is void: :number
error in process filter: Symbol’s function definition is void: :number
```

### Describe your attempts to resolve the issue

I looked into the `parseclj-lex--leaf-token-value: Symbol’s function definition is void: :number` error message, and found an earlier Doom Emacs [issue](https://github.com/hlissner/doom-emacs/issues/4539) about the same exact error message.

Unfortunately, `doom build` (as recommended in that issue) did not resolve the problem on my end.

I asked in the #help channel on the Doom discord, and was recommended to try:
1. Deleting the package manually from `~/.emacs.d/.local/straight/repos/`, then `doom sync`ing and restarting Emacs, and
2. Using `M-x find-function RET parseclj-parser` to find the package where it's defined, and byte-compiling it manually with `M-x byte-compile-file`

Unfortunately, neither of these steps resolved the issue.

### Steps to reproduce

1. I removed my current install of Doom Emacs and personal config files, then reinstalled Doom Emacs:
```shell
rm -rf ~/.emacs.d
rm -rf ~/.doom.d
git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
~/.emacs.d/bin/doom install
```
2. I installed the Clojure module by uncommenting the `clojure` line in the default init.el and then running `doom sync` This runs and installs successfully. 
3. I open Emacs and navigate to a cljs buffer that is part of a Shadow project.
4. I enable `explain-pause-mode` with `SPC h d d`
5. I hit `SPC m "` to run `cider-jack-in-cljs
6. The `Select ClojureScript REPL type:` prompt shows up; the "Basic face for shadowed text" column started happening when this issue did, though I'm not sure why it's happening: 
![Screen Shot 2021-10-02 at 3 47 20 PM](https://user-images.githubusercontent.com/7403854/135730005-3be2a00d-a302-4684-a247-bfad9e0b4ea6.png)
7. I select shadow, and receive this backtrace:
```emacs-lisp
Debugger entered--Lisp error: (void-function :number)
  :number(0)
  parseclj-lex--leaf-token-value(((:token-type . :keyword) (:form . ":source-paths") (:pos . 31)))
  parseedn-reduce-leaf((((:token-type . :lbrace) (:form . "{") (:pos . 30))) ((:token-type . :keyword) (:form . ":source-paths") (:pos . 31)) ((:tag-readers (shadow/env . identity))))
  parseclj-parser(parseedn-reduce-leaf parseedn-reduce-branch ((:tag-readers (shadow/env . identity))))
  parseedn-read(((shadow/env . identity)))
  cider--shadow-get-builds()
  cider-shadow-cljs-init-form()
  cider-cljs-repl-form(shadow)
  cider--update-cljs-init-function((:project-dir "~/Dropbox/projects/mccross.in/" :jack-in-cmd "/opt/homebrew/bin/npx shadow-cljs -d nrepl/nrepl:0..." :host "localhost" :port 57522 :project-dir "~/Dropbox/projects/mccross.in/" :server #<process nrepl-server> :server-command "/opt/homebrew/bin/npx shadow-cljs -d nrepl/nrepl:0..." :cljs-repl-type shadow))
  cider-connect-sibling-cljs((:project-dir "~/Dropbox/projects/mccross.in/" :jack-in-cmd "/opt/homebrew/bin/npx shadow-cljs -d nrepl/nrepl:0...") #<buffer  *nrepl-server projects/mccross.in:localhost*>)
  #f(compiled-function (server-buffer) #<bytecode 0x444a42cb>)(#<buffer  *nrepl-server projects/mccross.in:localhost*>)
  nrepl-server-filter(#<process nrepl-server> "shadow-cljs - server version: 2.15.10 running at h...")
  apply(nrepl-server-filter (#<process nrepl-server> "shadow-cljs - server version: 2.15.10 running at h..."))
  explain-pause--wrap-callback(#s(explain-pause-command-record :command process-filter :native nil :parent #s(explain-pause-command-record :command "nrepl-server" :native nil :parent #s(explain-pause-command-record :command cider-jack-in-cljs :native nil :parent #s(explain-pause-command-record :command root-emacs :native nil :parent nil :executing-time 45155 :entry-snap (24920 46912 843004 0) :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 0) :executing-time 20 :entry-snap (24920 46884 253873 0) :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 1) :executing-time 0 :entry-snap nil :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 2) :executing-time 0 :entry-snap nil :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 3) nrepl-server-filter #<process nrepl-server> "shadow-cljs - server version: 2.15.10 running at h...")
  apply(explain-pause--wrap-callback #s(explain-pause-command-record :command process-filter :native nil :parent #s(explain-pause-command-record :command "nrepl-server" :native nil :parent #s(explain-pause-command-record :command cider-jack-in-cljs :native nil :parent #s(explain-pause-command-record :command root-emacs :native nil :parent nil :executing-time 45155 :entry-snap (24920 46912 843004 0) :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 0) :executing-time 20 :entry-snap (24920 46884 253873 0) :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 1) :executing-time 0 :entry-snap nil :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 2) :executing-time 0 :entry-snap nil :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 3) nrepl-server-filter (#<process nrepl-server> "shadow-cljs - server version: 2.15.10 running at h..."))
  #f(compiled-function (&rest callback-args) #<bytecode 0x444a441b>)(#<process nrepl-server> "shadow-cljs - server version: 2.15.10 running at h...")
```

### System Information

https://pastebin.com/8aRZTvGj

I should note that I'm on an Apple Silicon machine, using `emacs-mac` from Homebrew. 
`M-x version` reports `GNU Emacs 27.2 (build 1, aarch64-apple-darwin20.4.0, Carbon Version 164 AppKit 2022.44) of 2021-05-18`

**Comment by hlissner** [comment]
There have been several reports of this issue, on Discord and Github, but I don't know the cause of this. What I do know:

- This is a byte-code issue. `parseclj-lex--leaf-token-value` (a macro) isn't available at compile time, and is therefore treated as a (malformed) function call at runtime, causing the error.
- It seems `doom build` fixes it for some people and not others.
- Perhaps this issue has been resolved upstream? Try unpinning the package:
  1. Add `(unpin! cider)` to `~/.doom.d/packages.el`
  2. Run `doom sync -u` on the command line
  3. Restart Emacs

Unfortunately, I can't reproduce this by simply enabling the module, so unless the build or unpinning helps, I'm stumped. Will report back if a new lead crops up.

**Comment by LucianoLaratelli** [comment]
Thanks Henrik! Unfortunately, unpinning `cider` and doing `doom sync -u` doesn't resolve the issue either.

**Comment by khmelevskii** [comment]
The same for me

**Comment by hlissner** [comment]
On second look I realize `parseclj-lex--leaf-token-value` is _not_ a macro, which means the `parseclj` library simply isn't available at runtime. Which is odd, because `parseedn` (which is [what calls it](https://github.com/clojure-emacs/parseedn/blob/master/parseedn.el#L75)) loads it:

1. https://github.com/clojure-emacs/parseedn/blob/master/parseedn.el#L52 loads `parseedn-parser`
2. https://github.com/clojure-emacs/parseclj/blob/master/parseclj-parser.el#L32 loads `parseclj-lex` where [`parseclj-lex--leaf-token-value` is defined](https://github.com/clojure-emacs/parseclj/blob/master/parseclj-lex.el#L165).

So:

1. Can you confirm that the parsedn and parseclj packages are in `~/.emacs.d/.local/straight/repos/`?
2. Can you inspect the \*Messages\* buffer for errors or warnings _before_ you get that error? Perhaps this is the end of a longer chain reaction?

**Comment by LucianoLaratelli** [comment]
1. Yes, they both are.
2. Nope, there's nothing else there. This is all that's in there starting from a fresh launch:
```
Doom loaded 180 packages across 31 modules in 0.777s [2 times]
Loading /Users/luciano/.emacs.d/.local/cache/recentf...done
Quit [2 times]
Waiting for git... [2 times]
[nREPL] Starting server via /opt/homebrew/bin/npx shadow-cljs -d nrepl/nrepl:0.9.0-beta3 -d cider/piggieback:0.5.2 -d refactor-nrepl/refactor-nrepl:2.5.1 -d cider/cider-nrepl:0.27.1 server
[nREPL] server started on 58063
error in process filter: parseclj-lex--leaf-token-value: Symbol’s function definition is void: :number
error in process filter: Symbol’s function definition is void: :number
Quit
evil-line-move: Beginning of buffer [4 times]
```

**Comment by LucianoLaratelli** [comment]
Also, I should note (courtesy of my friend @djeis97) that if I go into `~/.emacs.d/.local/straight/build-27.2/parseclj/`, remove the .elc files, and then restart emacs, that I can successfully select Shadow.

**Comment by caleb** [comment]
thanks @LucianoLaratelli! I should probably learn more about how emacs works, but it doesn't look like the elc files are regenerated on doing a `doom upgrade` or `doom sync`.

Will those modules just run slower without being compiled?

**Comment by hlissner** [comment]
Will those modules just run slower without being compiled?

Typically, yes.

> but it doesn't look like the elc files are regenerated on doing a doom upgrade or doom sync.

Neither of those commands are in charge of building uncompiled packages, only _re_building them when their elc is outdated. `doom build` is what you want.

**Comment by hlissner** [comment]
> Also, I should note (courtesy of my friend @djeis97) that if I go into `~/.emacs.d/.local/straight/build-27.2/parseclj/`, remove the .elc files, and then restart emacs (without `doom sync`ing or anything), that I can successfully select Shadow.

In that case, the workaround will be:

```elisp
;; add to ~/.doom.d/packages.el
(package! parseclj :recipe (:build (:not compile)))
```

Then run `doom sync -u` and restart Emacs.

**Comment by hlissner** [comment]
I'm hoping 62c25afd0fd14ef8a038ab73c5d2b5cc90bb64f5 would indirectly fix this issue. Could you try upgrading Doom? If it doesn't work at first, try deleting the packages by hand first:

```sh
rm -rf ~/.emacs.d/.local/straight/repos/parse*
doom sync
```

**Comment by LucianoLaratelli** [comment]
Didn't work at first nor after the manual deletion.

**Comment by hlissner** [comment]
Is this still an issue? The clojure module (and its parse* packages) have seen dozens of bumps since this was opened.

**Comment by LucianoLaratelli** [comment]
As far as I can tell it's been resolved.

I still see the `Basic face for shadowed text` text when selecting a REPL type, but that doesn't affect functionality.

**Comment by LucianoLaratelli** [comment]
Will close.

> By reporting the issues directly we can attend them directly and swiftly.

Will do so next time, thank you for the explanation and the comment!
