### ISSUE TITLE
Native compilation stuck on 2 files because of vterm

### ISSUE THREAD

**Issue by MithicSpirit** [doomemacs/doomemacs#5592]
### What did you expect to happen?

`doom sync`/`doom upgrade` should be able to successfully natively compile everything that it tries to.

### What actually happened?

Doom usually gets stuck on compiling 2 files (which can be checked with `ps`/`htop`/etc.):
```
/usr/bin/emacs --batch -l /tmp/emacs-async-comp-evil-collection-vterm-VTDFTP.el
/usr/bin/emacs --batch -l /tmp/emacs-async-comp-with-editor-rkp4J5.el
```
(Note: the ending of the filename appears to be randomized each run.)
After running these commands manually, the issue appears to be that they both prompt the user to compile `vterm-module`, which is never done since the user is not given access to this prompt. This is corroborated by the fact that `…/.emacs.d/.local/straight/build-28.0.60/vterm` is included in the `load-path` for both of these. Note that it is necessary to test these separately since, if `vterm-module` is already compiled (as a result from running one of these, for example), it will not prompt for compilation again. This also suggests that it may be possible to avoid this issue by compiling `vterm-module` prior to natively compiling these files, though IIRC this is considered to be outside the scope of Doom, so it may be better to just disable compiling these two altogether.

### Describe your attempts to resolve the issue

This can be worked around by just hitting `<C-c>` in the terminal and then re-running the command, though I believe this means that the files did not actually get natively compiled, which may reduce performance.

### Steps to reproduce

The easiest way to reproduce this is to force Emacs to recompile everything by deleting the straight folder:

1. Delete/trash the `~/.emacs.d/.local/straight` folder
2. Make sure the `:term vterm` module is enabled in your private `init.el`
3. Run `doom sync`
4. Wait a while until it gets to the end of the native compilation part (when it gets down to 2 files, or sooner if it appears to be stuck already)

Then, if you want to check the same stuff I did above,

5. Search running processes for "`/usr/bin/emacs`" (e.g.: `ps -aux | grep /usr/bin/emacs`); there should be 2 results (excluding `grep` itself)
6. Execute either of those manually in a shell—you will be prompted to compile vterm-module

### System Information

https://pastebin.com/zX9QYe08

**Comment by hlissner** [comment]
Possible duplicate of #4517 and #3683.

I can't reproduce this. Your best bet is to add a regexp to match those elisp files to `native-comp-deferred-compilation-deny-list`.

**Comment by MithicSpirit** [comment]
@fapapa Yeah, that much has been the determined. The main issue is actually that these files are supposed to be blocked from being compiled due to the `native-comp-deferred-compilation-deny-list` variable, but Emacs is attempting to compile them anyways.

**Comment by agzam** [comment]
_Sorry, I didn't know where to address this thought. I think I asked in Discord a couple of times, but it has gotten lost._

Has anyone proposed the idea of [optionally] skipping the native comp step in the doom cmd and doing it asynchronously in Emacs? It really sucks when you can't even use Doom while it's compiling a ton of stuff.

**Comment by MithicSpirit** [comment]
That might be a good idea for the CLI rewrite coming soon™ (#4273).

**Comment by hyiltiz** [comment]
@fapapa's suggestions above worked. Specifically, after running `ps aux|grep async`, I found that this command is running so I ran in a separate bash terminal: `/usr/local/bin/emacs --batch -l /tmp/emacs-async-comp-evil-collection-vterm-tn4Lyq.el` which prompted for a `y/n` for a totally trivial reason (see below). This is definitely a bug in the upstream, for demanding user interaction when none was reasonably required. 
```
Vterm needs `vterm-module' to work.  Compile it now? (y or n) y
```

But I wish doom could somehow detect these and just assume the default answer; no one who wants `vterm` would say no to these if `vterms` demands another dependency (unless it depends on something unreasonable like Wine).

**Comment by finex** [comment]
I confirm what @hyiltiz described on his comment.

**Comment by tecosaur** [comment]
I think the issue may be that the regexps in `core.el` doesn't account for the temp file suffixes.
https://github.com/hlissner/doom-emacs/blob/a46f741a89bb9a6df006a6b8875a840513ceb619/core/core.el#L168-L169

If I look at `ps -aux` I see that the evil collection vterm file is `evil-colection-vterm-zhm7dH.el`.

**Comment by MithicSpirit** [comment]
Oh great idea! I think that it might be sufficient to prepend a `.*` to the file extension.
I can't test rn but I'll try later.

**Comment by jbenden** [comment]
@MithicSpirit It does seem to work. I was able to get mine working with `.*` in front of `\\.el\\'`.

```
            (list (concat local-dir-re ".*/evil-collection-vterm.*\\.el\\'")
                  (concat local-dir-re ".*/with-editor.*\\.el\\'"))))))
```

**Comment by MithicSpirit** [comment]
Oh oops I totally forgot about this issue, sorry guys. Just tested it but it didn't work for me. Here's the diff:
```diff
diff --git a/core/core.el b/core/core.el
index c74f5b03..e1a2a1cb 100644
--- a/core/core.el
+++ b/core/core.el
@@ -165,8 +165,8 @@ users).")
     ;; HACK Disable native-compilation for some troublesome packages
     (mapc (doom-partial #'add-to-list 'native-comp-deferred-compilation-deny-list)
           (let ((local-dir-re (concat "\\`" (regexp-quote doom-local-dir))))
-            (list (concat local-dir-re ".*/evil-collection-vterm\\.el\\'")
-                  (concat local-dir-re ".*/with-editor\\.el\\'"))))))
+            (list (concat local-dir-re ".*/evil-collection-vterm.*\\.el\\'")
+                  (concat local-dir-re ".*/with-editor.*\\.el\\'"))))))
 
 
 ;;
```

**Comment by jbenden** [comment]
@MithicSpirit The `native-comp-deferred-compilation-deny-list` was the rename for an older `comp-deferred-compilation-black-list`. Maybe your version of Emacs is old?

**Comment by MithicSpirit** [comment]
I think this is the latest currently available. Not quite on the latest commit possible but relatively up-to-date.
```sh
$ emacs --version | head -n1
GNU Emacs 28.0.90
```

Also, checking `SPC h v` shows that `comp-deferred-compilation-black-list` doesn't exist, while `native-comp-deferred-compilation-deny-list` does and is properly documented, so I think I'm fine on that front. 

On further inspection though, it seems like `local-dir-re` might be the issue, since that ends up being ``\\`/home/mithic/\\.config/emacs/\\.local/``, while during the actual compilation the files are placed in `/tmp`.

**Comment by Seme4eg** [comment]
have same issue on both systems - arch and windows.

**Comment by nipuna-perera** [comment]
Same issue here, but killing the stuck process didn't really cause any issues. I was able to load emacs and compile vterm within.

**Comment by telotortium** [comment]
I've had a similar issue - I sometimes see an error in `doom-themes-ext-visual-bell.el` when rebuilding my packages, usually after upgrading Doom:

```
(signal doom-package-error ("doom-themes" (error "doom-themes-ext-visual-bell.el:0:0: error: cl-assertion-failed: ((> (point) output-start))")))
```

I've been able to fix this by denying this file from native compilation in my personal `init.el`:

```
(when NATIVECOMP
  (with-eval-after-load 'comp
    ;; HACK Disable native-compilation for some troublesome packages
    (mapc (apply-partially #'add-to-list 'native-comp-deferred-compilation-deny-list)
          (let ((local-dir-re (concat "\\`" (regexp-quote doom-local-dir))))
            (list (concat local-dir-re ".*/doom-themes-ext-visual-bell\\.el\\'"))))))
```

**Comment by hlissner** [comment]
Sorry for the tremendously long wait. As of fb7f4c6 I've implemented a timeout mechanism, so hanging comp.el processes will be killed after 30s of no movement before carrying on. With that I'll consider this issue resolved on Doom's end. Let me know if the issue crops up again. Thanks for bringing it to my attention!

**Comment by mangkoran** [comment]
@hakanserce With the commit above (https://github.com/doomemacs/doomemacs/commit/fb7f4c6cbed20fbefd9f18919e30d7405df83597) there is no need to use those method. You should be asked to compile vterm inside Emacs whenever you want to use vterm. CMIIW.

**Comment by edgar-vincent** [comment]
I still seem to be running into this issue, although Doom is up-to-date here. Am I the only one?

**Comment by agzam** [comment]
@edgar-vincent No, you're not the only one. I got so tired of dealing with it, that eventually I disabled vterm in my config. It still gets stuck for me (Intel-based Mac).

**Comment by Seme4eg** [comment]
fixed for me, using artix linux, emacs-native-comp and having vterm *uncommented* in init.el, nothing 'patched' or 'changed' anywhere, just ran doom install and everything went fine, vterm asked to be compiled when i first called it. The only thing is - when i was natively compiling all packages i didn't have cmake installed, installed it later when vterm has thrown an error that it's required.

**Comment by danilevy1212** [comment]
This is happening to me too on my M1 MacOS, vterm module is to blame.

**Comment by hlissner** [comment]
I think this can be fixed by making our deny-list regexps a little less precise. Please try this and see if the hanging no longer occurs:

```elisp
;;; in $DOOMDIR/init.el
(after! comp
  ;; HACK Disable native-compilation for some troublesome packages
  (mapc (doom-partial #'add-to-list 'native-comp-deferred-compilation-deny-list)
        (list "/emacs-jupyter.*\\.el\\'"
              "/evil-collection-vterm\\.el\\'"
              "/with-editor\\.el\\'")))
```

**Comment by edgar-vincent** [comment]
It does not seem to work for me, but I don't know if I'm testing it properly. After a fresh `doom install`, I added your snippet in `$DOOMDIR/init.el`, then ran `doom sync` and `doom build -r`. Compilation is still stuck on eshell- vterm:

` 210927 pts/1    Ssl+   0:00 /usr/sbin/emacs --batch -l /tmp/emacs-async-comp-eshell-vterm-2XBlfS.el`

Is that because `eshell-vterm.el` needs to be added to the list? This is a package that I added myself, and presumably it requires vterm to be installed. There is no reason to add it to the list because it is not included in Doom. However, it fails because of vterm, which is included in Doom.

**Comment by MithicSpirit** [comment]
@edgar-vincent until there is a general solution that automatically detects and cancels building files which request to compile vterm or blocks them from doing so, you'll need to add manually added packages to the deny list yourself.

**Comment by edgar-vincent** [comment]
@MithicSpirit Makes sense! Thank you.

**Comment by danilevy1212** [comment]
Does it have to be inserted into `init.el`? Or can it be added into `cli.el` instead?

**Comment by hlissner** [comment]
@danilevy1212 It's not required, no. It can be in either `init.el` or `cli.el`. (And to be even more confusing: in the future, package manager settings can also be set from `packages.el`).

**Comment by danilevy1212** [comment]
Thanks Henrik!

**Comment by hlissner** [comment]
As of c901f58, this should finally be resolved (at least for Straight). Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
