### ISSUE TITLE
`file-missing: Doing vfork` error during startup on MacOS Monterey (12.6)

### ISSUE THREAD

**Issue by neolee** [doomemacs/doomemacs#6809]
### What did you expect to happen?

Start Emacs with no weird error message.

### What actually happened?

Start Emacs, and after a while this message appears in *Messages* buffer:

```
Error: failed to incrementally load magit because: (file-missing Doing vfork No such file or directory)
```

Actually if I open treemac window or resize the Emacs window the error message seems to more likely jump out immediately.

### Describe your attempts to resolve the issue

N/A

### Steps to reproduce

Just open Emacs, open *Messages* buffer, wait to see it.

### System Information

https://pastebin.com/kV8QNKMM

**Comment by hlissner** [comment]
Please produce [a backtrace](https://discourse.doomemacs.org/t/what-is-a-backtrace-how-to-produce-them/85#how-to-produce-a-backtrace-3) from the error.

**Comment by hlissner** [comment]
This appears to be an upstream issue on macOS Monterey: https://twitter.com/jperkin/status/1455940516294676484

I'll leave this open until I hear the situation has changed.

(Thanks to @elken for letting me know on Discord)

**Comment by elken** [comment]
Just to further clarify; this _should_ have been resolved by now.

Both emacs-mac and emacs-plus have produced patches for it, and the fact you're on 28.2 suggests you've got them either way.

So, unless you can provide an actionable backtrace; I don't think there's anything to be done

**Comment by neolee** [comment]
After a fully rebuild of all installed package (and re-native-comp), and clean of some old Emacs cache file, the error message has gone, at lease for now.

p.s I'm using Emacs 28.2 built through the Homebrew d12frosted/emacs-plus formulae.

**Comment by elken** [comment]
Probably fine to close this then @hlissner

**Comment by dustinfarris** [comment]
@neolee can you share what cache you cleaned or any other steps?  I'm still getting this (started after upgrading from 28.1 to 28.2 using emacs-mac on homebrew)

**Comment by dustinfarris** [comment]
I got this after upgrading from 28.1 to 28.2 (via [emacs-mac](https://github.com/railwaycat/homebrew-emacsmacport) on homebrew) and also incidentally upgraded from Monterey 12.5 to 12.6 at the same time — which had its own weirdness with [clang not being found](https://www.reddit.com/r/MacOS/comments/xdjfb0/monterey_126_broken_git/), but in my case it was emacsql-sqlite that was causing the issue (not found).

I did this to flush out old 28.1 stuff (not sure if it was necessary)

```
rm -rf ~/.emacs.d/.local
doom sync
```

And then manually compiled emacsql-sqlite

```
cd .emacs.d/.local/straight/build-28.2/emacsql-sqlite/sqlite
make
```

Things seem to be working ok now.

**Comment by roiholtzman** [comment]
> Thanks @hlissner @elken !
> 
> After a fully rebuild of all installed package (and re-native-comp), and cleaning of some old Emacs cache files, the error message has gone, at lease for now.
> 
> p.s I'm using Emacs 28.2 built through the Homebrew d12frosted/emacs-plus formulae.

@neolee I am having now the same issue. Can you please explain the steps to solve it? Thanks so much!

**Comment by wehlutyk** [comment]
I can second that https://github.com/doomemacs/doomemacs/issues/6809#issuecomment-1976183218 ,  the problem appeared to me a few days ago:

`Error running timer: (file-missing "Doing vfork" "No such file or directory")`

This using the latest doomemacs bea81278fd2ecb65db6a63dbcd6db2f52921ee41, on Guix
```shell
$ guix describe
Generation 7	Mar 01 2024 22:23:53	(current)
  nonguix b6d05db
    repository URL: https://gitlab.com/nonguix/nonguix
    branch: master
    commit: b6d05dbefd2664aa6706d13ec4f46526a814369f
  guix-science 26fba1a
    repository URL: https://github.com/guix-science/guix-science.git
    branch: master
    commit: 26fba1a759f67f2c6c22049994db328550d45e30
  guix 9038a46
    repository URL: https://git.savannah.gnu.org/git/guix.git
    branch: master
    commit: 9038a46751c5090246e64b63ff752064833c435b
```

**Comment by wehlutyk** [comment]
Now apologies, this doesn't seem to appear any more -- so one upgrade might have actually fixed it.

**Comment by maikol-solis** [comment]
I came from here: https://discord.com/channels/406534637242810369/1273298103646027817/1273298103646027817

And I'm using emacs-plus 29.4 in macOS Ventura 13.6.7 (22G720)

For me the problem is when I try to use corfu in a org file. 

```lisp 
Debugger entered--Lisp error: (file-missing "Doing vfork" "No such file or directory")
  signal(file-missing ("Doing vfork" "No such file or directory"))
  (condition-case err (let* ((checker (flycheck-get-checker-for-buffer))) (if checker (flycheck-start-current-syntax-check checker) (flycheck-clear) (flycheck-report-status 'no-checker))) (error (flycheck-report-failed-syntax-check) (signal (car err) (cdr err))))
  (if (flycheck-running-p) nil (run-hooks 'flycheck-before-syntax-check-hook) (flycheck-clear-errors) (flycheck-mark-all-overlays-for-deletion) (condition-case err (let* ((checker (flycheck-get-checker-for-buffer))) (if checker (flycheck-start-current-syntax-check checker) (flycheck-clear) (flycheck-report-status 'no-checker))) (error (flycheck-report-failed-syntax-check) (signal (car err) (cdr err)))))
  (if flycheck-mode (if (flycheck-running-p) nil (run-hooks 'flycheck-before-syntax-check-hook) (flycheck-clear-errors) (flycheck-mark-all-overlays-for-deletion) (condition-case err (let* ((checker (flycheck-get-checker-for-buffer))) (if checker (flycheck-start-current-syntax-check checker) (flycheck-clear) (flycheck-report-status 'no-checker))) (error (flycheck-report-failed-syntax-check) (signal (car err) (cdr err))))) (user-error "Flycheck mode disabled"))
  flycheck-buffer()
  (condition-case err (flycheck-buffer) ((debug error) (message "Error while checking syntax automatically: %S" err) nil))
  (if (or force-deferred (flycheck-must-defer-check)) (flycheck-buffer-deferred) (condition-case err (flycheck-buffer) ((debug error) (message "Error while checking syntax automatically: %S" err) nil)))
  (progn (flycheck--clear-idle-trigger-timer) (setq flycheck--idle-trigger-conditions nil) (if (or force-deferred (flycheck-must-defer-check)) (flycheck-buffer-deferred) (condition-case err (flycheck-buffer) ((debug error) (message "Error while checking syntax automatically: %S" err) nil))))
  (if (and flycheck-mode (if (listp condition) (apply #'flycheck-may-check-automatically condition) (flycheck-may-check-automatically condition))) (progn (flycheck--clear-idle-trigger-timer) (setq flycheck--idle-trigger-conditions nil) (if (or force-deferred (flycheck-must-defer-check)) (flycheck-buffer-deferred) (condition-case err (flycheck-buffer) ((debug error) (message "Error while checking syntax automatically: %S" err) nil)))))
  flycheck-buffer-automatically((idle-change))
  (progn (flycheck-buffer-automatically flycheck--idle-trigger-conditions) (setq flycheck--idle-trigger-conditions nil))
  (if flycheck--idle-trigger-conditions (progn (flycheck-buffer-automatically flycheck--idle-trigger-conditions) (setq flycheck--idle-trigger-conditions nil)))
  (save-current-buffer (set-buffer buffer) (if (or flycheck-buffer-switch-check-intermediate-buffers (eq buffer current-buffer)) nil (setq flycheck--idle-trigger-conditions (delq 'idle-buffer-switch flycheck--idle-trigger-conditions))) (if flycheck--idle-trigger-conditions (progn (flycheck-buffer-automatically flycheck--idle-trigger-conditions) (setq flycheck--idle-trigger-conditions nil))))
  (progn (save-current-buffer (set-buffer buffer) (if (or flycheck-buffer-switch-check-intermediate-buffers (eq buffer current-buffer)) nil (setq flycheck--idle-trigger-conditions (delq 'idle-buffer-switch flycheck--idle-trigger-conditions))) (if flycheck--idle-trigger-conditions (progn (flycheck-buffer-automatically flycheck--idle-trigger-conditions) (setq flycheck--idle-trigger-conditions nil)))))
  (if (buffer-live-p buffer) (progn (save-current-buffer (set-buffer buffer) (if (or flycheck-buffer-switch-check-intermediate-buffers (eq buffer current-buffer)) nil (setq flycheck--idle-trigger-conditions (delq 'idle-buffer-switch flycheck--idle-trigger-conditions))) (if flycheck--idle-trigger-conditions (progn (flycheck-buffer-automatically flycheck--idle-trigger-conditions) (setq flycheck--idle-trigger-conditions nil))))))
  (let ((current-buffer (current-buffer))) (if (buffer-live-p buffer) (progn (save-current-buffer (set-buffer buffer) (if (or flycheck-buffer-switch-check-intermediate-buffers (eq buffer current-buffer)) nil (setq flycheck--idle-trigger-conditions (delq 'idle-buffer-switch flycheck--idle-trigger-conditions))) (if flycheck--idle-trigger-conditions (progn (flycheck-buffer-automatically flycheck--idle-trigger-conditions) (setq flycheck--idle-trigger-conditions nil)))))))
  flycheck--handle-idle-trigger(#<buffer bitacora_1.org>)
  apply(flycheck--handle-idle-trigger #<buffer bitacora_1.org>)
  timer-event-handler([t 26301 4739 850518 nil flycheck--handle-idle-trigger (#<buffer bitacora_1.org>) nil 0 nil])
```

Thanks for your help.

**Comment by ZelphirKaltstahl** [comment]
This seems perhaps not only doomemacs related and also not MacOS related. I see this happening in vanilla Emacs (though heavily customized) and on GNU/Linux. Also installed Emacs using GNU Guix:

```scheme
(list (channel
        (name 'guix)
        (url "https://git.savannah.gnu.org/git/guix.git")
        (branch "master")
        (commit
          "b3b98151f30552357b91154deb6cc71696af5537")
        (introduction
          (make-channel-introduction
            "9edb3f66fd807b096b48283debdcddccfea34bad"
            (openpgp-fingerprint
              "BBB0 2DDF 2CEA F6A8 0D1D  E643 A2A0 6DF2 A33A 54FA")))))
```
