### ISSUE TITLE
Localleader `,` doesn't work in clojure-mode since ca90c5e83

### ISSUE THREAD

**Issue by or** [doomemacs/doomemacs#7130]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When I use `(setq doom-localleader-key ",")` in my `config.el`, it should allow me to use `,` instead of `SPC m` as the local leader key, in particular in `clojure-mode`.

### Current behavior

The local leader doesn't work in `clojure-mode` anymore. `SPC m` still shows the expected menu, but `,` triggers `evil-repeat-find-char-reverse`.
I saw nothing of interest in `*Messages*`.

I've bisected the recent git history and found that https://github.com/doomemacs/doomemacs/commit/ca90c5e83 appears to be the culprit. If I revert this commit and run `doom clean; doom sync -u`, then everything works as it should again.

### Steps to reproduce

1. Have an empty `config.el`, add `(setq doom-localleader-key ",")`,
2. I've also enabled `(clojure +lsp)` in `init.el`, tho neither removing `lsp` nor commenting out the whole line seems to make a difference for the behaviour.
3. Run `doom clean; doom sync -u`,
4. Start emacs, open a Clojure or ClojureScript file (*.clj or *.cljs).
5. Press `,`, it invokes `evil-repeat-find-char-reverse`, it doesn't bring up the menu.

### System Information

https://pastebin.com/V6jK43C8

**Comment by elken** [comment]
I've had someone else confirm this now so I can confirm it's an issue. I'm looking into it now :)

**Comment by jasonjckn** [comment]
moving  doom-localleader-key "," from config.el to top of init.el fixed it for me

**Comment by elken** [comment]
> moving (setq doom-localleader-key ",") from config.el to top of init.el fixed it for me

Yes as per a discussion on slack, this also seems to resolve it so I'm marking the PR as a draft for now

**Comment by corasaurus-hex** [comment]
Confirming what @lycheese said, localleader is no longer bound (I'm using a fresh install with just `(clojure +lsp)` and `lsp` uncommented).

**Comment by hlissner** [comment]
@corasaurus-hex I'm struggling to reproduce this whether or not I alter `doom-localleader-key`.

Are there any errors/warnings in \*Messages\* after opening your first clojure buffer? (`C-h e` will open that buffer)

**Comment by dpr10** [comment]
@hlissner the issue appears for me when LSP is enabled for clojure module, without that everything seems to work as intended.
Side note, the issue appears despite the local leader it's changed or not.

**Comment by corasaurus-hex** [comment]
Wait, no, that comment from @elken was posted on the 10th so this wouldn't be resolved.

**Comment by elken** [comment]
[f47356d](https://github.com/elken/doomemacs/commit/f47356df964b39427aff24e6652d526b35d7058c) should fix it

**Comment by SavageMessiah** [comment]
I'm also having this issue with clojure and LSP. Moving `(setq doom-localleader-key ",")` to init.el didn't help but reverting https://github.com/doomemacs/doomemacs/commit/719716cf2049bef1fa46a159a5e2ce33301ec4d3 and https://github.com/doomemacs/doomemacs/commit/ca90c5e83caa86e0a5adb098a8e7015555137e36 did the job.

**Comment by corasaurus-hex** [comment]
@hlissner apologies for the delay.

I have an entirely fresh doom install.

<details>
<summary>Environment</summary>
```
❯ emacs --version
GNU Emacs 28.2

❯ brew info emacs-plus@28
==> d12frosted/emacs-plus/emacs-plus@28: stable 28.2, HEAD
/usr/local/Cellar/emacs-plus@28/28.2 (4,411 files, 175.3MB) *
  Built from source on 2023-01-21 at 19:24:11 with: --with-xwidgets --with-native-comp --with-imagemagick --with-elrumo2-icon
From: https://github.com/d12frosted/homebrew-emacs-plus/blob/HEAD/Formula/emacs-plus@28.rb
==> Dependencies
Build: make ✔, autoconf ✔, gnu-sed ✔, gnu-tar ✔, awk ✔, coreutils ✔, pkg-config ✔, texinfo ✔, xz ✔
Required: gnutls ✔, librsvg ✘, little-cms2 ✔, jansson ✔
Optional: imagemagick ✘, dbus ✔, mailutils ✘

❯ doom doctor
The doctor will see you now...

> Checking your Emacs version...
> Checking for Doom's prerequisites...
> Checking for Emacs config conflicts...
> Checking for great Emacs features...
> Checking for private config conflicts...
> Checking for stale elc files...
> Checking for problematic git global settings...
> Checking Doom Emacs...
  ✓ Initialized Doom Emacs 3.0.0-pre
  ✓ Detected 34 modules
  ✓ Detected 130 packages
  > Checking Doom core for irregularities...
    Found font material-design-icons.ttf
    Found font weathericons.ttf
    Found font octicons.ttf
    Found font fontawesome.ttf
    Found font file-icons.ttf
    Found font all-the-icons.ttf
  > Checking for stale elc files in your DOOMDIR...
  > Checking your enabled modules...
    Some advanced consult filtering features will not work as a result, see the
    module readme.
    > :completion vertico
      ! The installed grep binary was not built with support for PCRE lookaheads

There is 1 warning!

❯ diff .config/doom/init.el .config/doom/init.original.el
98c98
<        lsp               ; M-x vscode
---
>        ;;lsp               ; M-x vscode
119c119
<        (clojure +lsp)           ; java with a lisp
---
>        ;;clojure           ; java with a lisp
```

`config.el` and `packages.el` are untouched.

</details>

When I open a clojure file and then hit `C-h e` the buffer reads:

```
Doom loaded 180 packages across 34 modules in 27.340s
[yas] Check your `yas-snippet-dirs': /Users/cora/.config/doom/snippets/ is not a directory
[yas] Prepared just-in-time loading of snippets with some errors.  Check *Messages*.
Switched to ’cljdoc’
Loading /Users/cora/.config/emacs/.local/cache/recentf...done
Note: standard-indent, tab-width, evil-shift-width adjusted to 2
LSP :: Connected to [clojure-lsp:35895/starting /Users/cora/Code/cljdoc].
LSP :: clojure-lsp:35895 initialized successfully in folders: (/Users/cora/Code/cljdoc)
```

As @mateodif said, if I `M-x clojure-mode` after that then the localleader is then bound.

If I change `(clojure +lsp)` to just `clojure` in `init.el` then `localleader` is bound correctly from the start with the following in the `*Messages*` buffer:

```
Doom loaded 180 packages across 34 modules in 0.930s
Switched to ’cljdoc’
Loading /Users/cora/.config/emacs/.local/cache/recentf...done
Note: standard-indent, tab-width, evil-shift-width adjusted to 2
[yas] Check your `yas-snippet-dirs': /Users/cora/.config/doom/snippets/ is not a directory
[yas] Prepared just-in-time loading of snippets with some errors.  Check *Messages*.
```

**Comment by paulocavaro** [comment]
Hey guys, I'm having the same issue. 

I have been trying:
- reinstall emacs and upgrade doom. 
-  `(setq doom-localleader-key ",")` at the top of init.el.
- [This changes here](https://github.com/elken/doomemacs/commit/f47356df964b39427aff24e6652d526b35d7058c) also didn't work for me.

**Comment by or** [comment]
This still doesn't work for me. I've done all the tests again, with a minimal config.el that only sets the localleader.

Reverting the two commits in https://github.com/doomemacs/doomemacs/issues/7130#issuecomment-1468736616 on top of the current master works for me.
