### ISSUE TITLE
Can not jump forward with C-i

### ISSUE THREAD

**Issue by kaiwk** [doomemacs/doomemacs#7997]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

jump forward with C-i, jump backward with C-o

### Current behavior

Can not jump forward with C-i, and jump backward sometimes work in a weird way.

### Steps to reproduce

In any project (or, for example, a C++ project with clangd), use C-i/C-o jump around you will find some weird behaviour.

### System Information

https://pastebin.com/RFfjXncX

**Comment by kaiwk** [comment]
It's probably related to https://github.com/gilbertw1/better-jumper/pull/26, and  https://github.com/doomemacs/doomemacs/commit/511c8af36537992fd60ff970e19e5638207546ed#diff-ebf0e1ac30f9979b61b57205b879e7bbf13177f885ef84e247357aaff71d8693L4

**Comment by hlissner** [comment]
As of 916180a this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by panchoh** [comment]
It’s happening to me now (with c0a1b9efc9a89c240fb8a76424c4d227dcbfc2d8 at least).
Here is my [config](https://github.com/panchoh/dotconfig-doom), and here is my [flake](https://github.com/panchoh/nixos).

I experience issues while navigating `./lib` and `./modules/lib` within [flake.nix](https://github.com/panchoh/nixos/blob/f85779de2a76797dfbfeff9118c2b0203c484688/flake.nix#L34). Just by pressing enter while the cursor is over `./lib` and `./modules/lib`, and doing the same with links within the `default.nix` buffer that it opens automatically, and trying to go back and forth with `C-o` and `C-i`, will render inconsistent and erratic behavior eventually (like returning to a different buffer, or positioning the cursor in the wrong place in the line).

<details>
<pre>
❯ doom info
generated  Aug 18, 2024 11:56:47
system     NixOS 24.11.20240814.c3aa7b8 (Vicuna) Linux 6.10.4 x86_64
emacs      29.4 EMACSDIR=~/.config/emacs/ EMACS=/nix/store/m0y0fkz0rag7a2niv57j865dr5jlly72-emacs-pgtk-29.4/bin/emacs
doom       3.0.0-pre PROFILE=_@0 HEAD -> master c0a1b9ef 2024-08-18 03:59:18 -0400 ~/.config/doom/
shell      /run/current-system/sw/bin/fish
features   CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LIBSELINUX LIBSYSTEMD LIBXML2 MODULES
	  NATIVE_COMP NOTIFY INOTIFY PDUMPER PGTK PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER
	  WEBP XIM XWIDGETS GTK3 ZLIB
traits     batch server-running
modules    :config use-package :completion (corfu +icons +orderless +dabbrev) (vertico +childframe +icons) :ui doom
	  doom-dashboard (emoji +ascii +github +unicode) hl-todo indent-guides (ligatures +extra) minimap modeline nav-flash
	  ophints (popup +all +defaults) (treemacs +lsp) unicode (vc-gutter +pretty) vi-tilde-fringe (window-select +numbers)
	  workspaces zen :editor (evil +everywhere) file-templates fold (format +lsp +onsave) snippets word-wrap :emacs (dired
	  +icons +dirvish) electric undo vc :term vterm :checkers (syntax +icons +flymake +childframe) (spell +flyspell
	  +everywhere) grammar :tools ansible (debugger +lsp) direnv (docker +lsp) editorconfig (eval +overlay) (lookup
	  +docsets +dictionary +offline) (lsp +peek) (magit +forge) make pdf terraform tmux tree-sitter :lang (cc +lsp
	  +tree-sitter) data emacs-lisp (go +lsp +tree-sitter) (graphql +lsp) (haskell +lsp +tree-sitter) (json +lsp
	  +tree-sitter) (javascript +lsp +tree-sitter) (latex +lsp) (markdown +grip) (nix +lsp +tree-sitter) (org +hugo
	  +pandoc +pomodoro +present +pretty +dragndrop +roam2) (python +lsp +pyenv +pyright +treesitter) (rest +jq) (sh +fish
	  +lsp +tree-sitter) (web +lsp +tree-sitter) (yaml +lsp +tree-sitter) :app emms :config (default +bindings
	  +smartparens)
packages   (pinentry) (pkgbuild-mode)
elpa       vterm base16-theme
</pre>
</details>

**Comment by panchoh** [comment]
> It’s happening to me now (with [c0a1b9e](https://github.com/doomemacs/doomemacs/commit/c0a1b9efc9a89c240fb8a76424c4d227dcbfc2d8) at least). Here is my [config](https://github.com/panchoh/dotconfig-doom), and here is my [flake](https://github.com/panchoh/nixos).
> 
> I experience issues while navigating `./lib` and `./modules/lib` within [flake.nix](https://github.com/panchoh/nixos/blob/f85779de2a76797dfbfeff9118c2b0203c484688/flake.nix#L34). Just by pressing enter while the cursor is over `./lib` and `./modules/lib`, and doing the same with links within the `default.nix` buffer that it opens automatically, and trying to go back and forth with `C-o` and `C-i`, will render inconsistent and erratic behavior eventually (like returning to a different buffer, or positioning the cursor in the wrong place in the line).

(pinging @hlissner, since my comment seems to have flown under the radar)

**Comment by deirn** [comment]
@panchoh, do you happen to use Emacs in daemon mode? I also encountered this issue only in it, regular run works just fine.
In the end what I did was to remap `C-i` to `H-i` and remap `H-i` manually:
```el
(defun my/C-i ()
  (when (display-graphic-p)
    (key-translate "C-i" "H-i")))

(my/C-i)
(add-hook 'after-make-frame-functions
          (lambda (frame)
            (with-selected-frame frame (my/C-i))))

(after! better-jumper
  (keymap-global-set "H-i" #'better-jumper-jump-forward))
```
I think it has to do with the after frame hook, from what I can tell `display-graphic-p` will be `nil` when starting the daemon and thus the workaround here didn't get called https://github.com/doomemacs/doomemacs/blob/2bc052425ca45a41532be0648ebd976d1bd2e6c1/lisp/doom-keybinds.el#L53-L75

<details><summary>Details</summary>
<p>

```
generated  Jan 26, 2025 14:40:00
system     NixOS 24.11.20250113.67e9c88 (Vicuna) Linux
           5.15.167.4-microsoft-standard-WSL2 x86_64 x
emacs      29.4 EMACSDIR=~/.config/emacs/
           EMACS=/nix/store/grllwhpn65r31v1q7pgx6wvlx3f5095a-emacs-29.4/bin/emacs
doom       3.0.0-pre PROFILE=_default@0 grafted, HEAD -> master, origin/master,
           origin/HEAD 2bc0524 2025-01-14 13:57:18 -0500 ~/.config/doom/
shell      /run/current-system/sw/bin/zsh
features   CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON
           LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY
           INOTIFY PDUMPER PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF
           TOOLKIT_SCROLL_BARS TREE_SITTER WEBP X11 XAW3D XDBE XIM XINPUT2 XPM LUCID
           ZLIB
traits     gui daemon server-running envvar-file
modules    :config use-package :completion (corfu +orderless) vertico :ui doom
           doom-dashboard hl-todo indent-guides minimap modeline ophints (popup
           +defaults) (treemacs +lsp) unicode (vc-gutter +pretty) vi-tilde-fringe
           window-select workspaces zen :editor (evil +everywhere) file-templates fold
           multiple-cursors snippets :emacs dired electric undo vc :term vterm
           :checkers syntax :tools direnv (eval +overlay) lookup lsp magit tree-sitter
           :os tty :lang emacs-lisp (java +lsp) markdown nix org sh yaml :config
           (default +bindings +smartparens)
packages   (elcord) (trashed)
elpa       vterm
```

</p>
</details>

**Comment by panchoh** [comment]
Thanks for the info, @deirn !

I’m not currently using daemon mode, but since I plan to going back to using it, this will be helpful.

I can confirm that the issue is still present for me (non-daemon mode), but I’ve yet to ascertain if I can reproduce it with a simple emacs config that only loads evil, since the problem might be an evil issue.

**Comment by hlissner** [comment]
@deirn's issue is unrelated to this one. Theirs is related to `C-i` not being bound to the correct command (see https://github.com/doomemacs/doomemacs/issues/8269).

-----

In any case, I suspect this has to do with better-jumper recording too many (or too few) jump points; seems to have coincided with some upstream changes some months ago to Evil's jumplist (which better-jumper integrates with). I haven't had time to look into it deeper yet.
