### ISSUE TITLE
`doom/reload` error: `line 12: c:/Program: No such file or directory` on  (Windows 11)

### ISSUE THREAD

**Issue by MrZaurik** [doomemacs/doomemacs#8098]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

The normal output (In my case, in order to do the doom sync I have to run it directly from Git Bash. Inside Doom it does not run.):

```
$ ~/.emacs.d/bin/doom sync -B -e
Package cl is deprecated
- Using Emacs 29.4 @ c:/Program Files/Emacs/emacs-29.4/bin/emacs.exe
> Synchronizing "default" profile...
  > Ensuring packages are installed and built...
    - No packages need attention
  > Updating pinned packages...
    - (100/145) vi-tilde-fringe is up-to-date
Package autoload is deprecated
    ✓ All 145 packages are up-to-date
  > Purging orphaned packages (for the emperor)...
    - Skipping builds
    - Skipping elpa packages
    - Skipping repos
    - Skipping regrafting
  > (Re)building profile in c:/Users/Juangui/.emacs.d/.local/etc/@/...
    > Deleting old init files...
    > Generating 4 init files...
    > Byte-compiling init.29.el...
    ✓ Built init.29.elc
  - Restart Emacs or use 'M-x doom/reload' for changes to take effect
✓ Finished in 11.33821s

```

### Current behavior

Currently and after executing the shortcut `SPC h r r` what I get is the following:

```
-*- mode: compilation; default-directory: "~/.emacs.d/" -*-
Comint started at Sun Sep 29 10:55:38

c:/Users/Juangui/.emacs.d/bin/doom sync -B -e
c:/Users/Juangui/.emacs.d/bin/doom: line 12: c:/Program: No such file or directory

Comint exited abnormally with code 127 at Sun Sep 29 10:55:38
```

### Steps to reproduce

1. For windows: download from the fd and ripgrep repositories their compressed files, extract them in Program Files and add their respective path to the environment variables.

3. Make a regular installation of Emacs

4. Clone the doom emacs repository in the ~/.emacs.d directory and make your usual installation.

5. Open emacs and verify that doom is installed correctly (as it is the case). So far, everything seems normal until you run Doom Sync from emacs... This will show what I showed previously, while waiting for the package synchronization to be done.

### System Information

https://pastebin.com/shGABdi2

**Comment by vlattaro** [comment]
I have the exact same problem here, running on windows 10 : 

$ doom info
Package cl is deprecated
generated  oct. 02, 2024 09:27:22
system     Windows Unknown MINGW64_NT-10.0-19045 3.1.7-340.x86_64 x86_64
emacs      29.3 EMACSDIR=~/.config/emacs/ EMACS=c:/Program Files/Emacs/emacs-29.3_2/bin/emacs.exe
doom       3.0.0-pre PROFILE=_@0 grafted, HEAD -> master, origin/master, origin/HEAD c8a5e6e 2024-09-17 17:30:57 -0400 ~/.config/doom/
shell      C:\Program Files\Git\usr\bin\bash.exe
features   ACL GIF GMP GNUTLS HARFBUZZ JPEG JSON LCMS2 LIBXML2 MODULES NATIVE_COMP NOTIFY W32NOTIFY PDUMPER PNG RSVG SOUND SQLITE3 THREADS TIFF
           TOOLKIT_SCROLL_BARS TREE_SITTER WEBP XPM ZLIB
traits     batch server-running envvar-file custom-file
modules    :config use-package :input (layout +azerty) :completion (corfu +orderless +icons) (vertico +childframe +icons) :ui doom doom-dashboard
           hl-todo indent-guides ligatures modeline nav-flash ophints (popup +defaults) (treemacs +lsp) unicode (vc-gutter +pretty) vi-tilde-fringe
           window-select workspaces zen :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors snippets word-wrap :emacs
           (dired +icons +dirvish) electric (ibuffer +icons) undo vc :term eshell shell term :checkers syntax (spell +flyspell) grammar :tools ein
           (eval +overlay) lookup (lsp +peek) magit pdf tmux tree-sitter :lang (cc +tree-sitter) emacs-lisp markdown (org +brain +roam2 +pretty
           +present +pomodoro +dragndrop +brain) (python +lsp +conda +ein +tree-sitter) (rust +lsp) sh :app calendar :config (default +bindings
           +smartparens)
packages   (org-roam-ui)
unpin      org-roam

**Comment by hlissner** [comment]
As of [8c77119](https://github.com/doomemacs/doomemacs/commit/8c7711920e6dfc2996200fde786bf1b09f58730f) this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by MrZaurik** [comment]
Hello again and thank you very much.

After installing the latest Powershell version so far (v. 7.4.5) and enabling Powershell script execution (it comes disabled by default) with the `Set-ExecutionPolicy RemoteSigned -Scope CurrentUser` command I have the following output when doing doom/reload:

`Powershell 3.0+ is required, but pwsh.exe was not found in your $PATH`

But I have the directory where pwsh.exe is added to the path. Which I don't understand.

![Image](https://github.com/user-attachments/assets/1a7daf05-ef9b-4312-940e-ac6947a64ba1)

**Comment by MrZaurik** [comment]
I solved the problem by putting the full path to pwsh.exe instead of just the command.

**Comment by vlattaro** [comment]
@hlissner Thanks for looking into it.

[8c77119](https://github.com/doomemacs/doomemacs/commit/8c7711920e6dfc2996200fde786bf1b09f58730f) has not fixed the problem for me.

I did some thinkering, moving the Emacs binary folder to a path that does not contain spaces has fixed the problem. Before, Emacs binary was located at C:\Program Files\Emacs\..., 

This behavior was not present before. Perhaps something related to path management in Windows?

**Comment by harishnkr** [comment]
Issue still persists

**Comment by meligonzalezn** [comment]
Hi, everyone!
Has anyone found a solution to this issue? I’ve tried the previously mentioned solutions, including adding the full path to `pwsh.exe`, but it didn’t work for me. Additionally, I haven’t been able to find much information about this problem. Thanks!

**Comment by meligonzalezn** [comment]
Has anyone found a solution to this issue? I’ve tried the previously mentioned solutions, including adding the full path to `pwsh.exe`, but it didn’t work for me. Additionally, I haven’t been able to find much information about this problem.

**Comment by harishnkr** [comment]
The only method in which I solved it is by using a file path without spaces

**Comment by DavideWiest** [comment]
One of the following lines added to config.el fixed the issue for me:
```
(add-to-list 'exec-path "C:/Program Files/PowerShell/7")
(setq shell-file-name "C:/Program Files/PowerShell/7/pwsh.exe")
(setq explicit-shell-file-name "C:/Program Files/PowerShell/7/pwsh.exe")
(setq vterm-shell "C:/Program Files/PowerShell/7/pwsh.exe")
```

**Comment by ronnac** [comment]
I had some success by replacing 'pwsh' by 'powershell' in bin/doom.ps1

**Comment by ronnac** [comment]
both executables exist. They are not entirely the same. One or the other might not be installed.

**Comment by hlissner** [comment]
Please try replacing the `bin/doom.ps1` file and the `doom--if-compile` macro in [lisp/lib/config.el](https://github.com/doomemacs/doomemacs/blob/master/lisp/lib/config.el#L29-L61) with [these](https://gist.github.com/hlissner/fa1e5b464eb04ec9751afcd93b1de882) and let me know if it fixes the issue. I am currently traveling and don't have a VM or Windows system handy to test on.

**Comment by ronnac** [comment]
I ran a "doom sync" without problems with these versions.
Question: why do you actually need the path to the powershell executable? Can't you use Invoke-Command?

**Comment by hlissner** [comment]
> Question: why do you actually need the path to the powershell executable? Can't you use Invoke-Command?

**The short answer:** I'm not 100% on powershell's syntax, don't have a local Windows system to iterate on atm, and `doom.ps1` is the only powershell script I've ever written (and likely ever will), so I ported bin/doom's [shebang line](https://github.com/doomemacs/doomemacs/blob/master/bin/doom#L3-L14) over naively. No surprise it could be written better.

Would this work?

```diff
    & $emacs -q --no-site-file --batch --load "$doom" -- --no-color $args
    if ($LASTEXITCODE -eq 254) {
-       & $pwsh "$($env:temp)\doom.$($env:__DOOMPID).$($env:__DOOMSTEP).ps1" $PSCommandPath $args
+       Invoke-Command -FilePath "$($env:temp)\doom.$($env:__DOOMPID).$($env:__DOOMSTEP).ps1" $PSCommandPath $args
        $exit = $LASTEXITCODE
    }
```

**The long answer:** On *nixes, Doom sometimes writes a temporary script to `/tmp/` to execute after the current `bin/doom` process ends, but users can mount `/tmp` with the noexec flag, preventing the direct execution of anything there, so I get around that by [passing the script to `bin/sh` instead](https://github.com/doomemacs/doomemacs/blob/master/bin/doom#L13), which was [naively ported to doom.ps1](https://github.com/doomemacs/doomemacs/blob/master/bin/doom.ps1#L27). I have no idea if anything like `noexec` exists on Windows, or if some odd combination of Cygwin or WSL (with linux mounts) cause similar file permission complications.

> I ran a "doom sync" without problems with these versions.

Awesome. I'll push it to `master` soon.

**Comment by ronnac** [comment]
I still have to test your Invoke-Command. In the meantime a different remark: There is an equivalent to the magic shebang, called [polyglot](https://stackoverflow.com/a/2611487) or hybrid DOS BATCH scripts. This is interesting, because files ending in .bat or .cmd can be called like DOS commands from the command line if they are on the windows path or in the current folder, so a polyglot doom.bat (which would actually contain powershell code) could be called by typing "doom".

**Comment by hlissner** [comment]
As of 589fa73 the original issue should be resolved, but I'll still look into magic shebangs and Invoke-Command to improve the ps1 script once I have a Windows environment to more proactively test in. 

Let me know if the issue resurfaces and I'll reopen this. Thanks for bringing it to my attention!
