### ISSUE TITLE
Doom upgrade (from: c6f749e67c to: ad0eb9d5a2) results in "Unexpected error in Doom’s core: "lisp/lib/files.el", (void-function static-unless)"

### ISSUE THREAD

**Issue by markflarup** [doomemacs/doomemacs#8359]
### I confirm that...

- [x] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [x] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [x] The issue can be reproduced on the **latest** available commit of Doom.

- [x] The issue can be reproduced on a stable release of Emacs, such as 27, 28, 29, or 30. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

I expected doom to upgrade successfully, but it fails with "Unexpected error in Doom’s core: "lisp/lib/files.el", (void-function static-unless)". I think it might be caused by commit [a13719a](https://github.com/doomemacs/doomemacs/commit/a13719af45133ca2f6520a7fe8139664fffc0c9b). This is the link to the full diff: https://github.com/doomemacs/doomemacs/compare/c6f749e67c13342007f6aeaa4a81e6fdb00f529f...ad0eb9d5a2259a67084ea855eb7ab7125376ff6b

### Current behavior

```
doom up
...

Error: doom-core-error ("lisp/lib/files.el" (void-function static-unless))
  signal(doom-core-error ("lisp/lib/files.el" (void-function static-unless)))
  (progn (signal err (list (file-relative-name path (expand-file-name "../" dir)) e)))
  (if (file-in-directory-p path dir) (progn (signal err (list (file-relative-name path (expand-file-name "../" dir)) e))))
  (while (consp --cl-var--) (setq dir (car --cl-var--) err (pop dir)) (if (file-in-directory-p path dir) (progn (signal err (list (file-relative-name path (expand-file-name "../" dir)) e)))) (setq --cl-var-- (cdr --cl-var--)))
  (let* ((--cl-var-- (list (cons 'doom-cli-error (expand-file-name "cli" doom-core-dir)) (cons 'doom-core-error doom-core-dir) (cons 'doom-user-error doom-user-dir) (cons 'doom-profile-error doom-profile-dir) (cons 'doom-module-error doom-modules-dir))) (dir nil) (err nil)) (while (consp --cl-var--) (setq dir (car --cl-var--) err (pop dir)) (if (file-in-directory-p path dir) (progn (signal err (list (file-relative-name path (expand-file-name "../" dir)) e)))) (setq --cl-var-- (cdr --cl-var--))) nil)
  (catch '--cl-block-nil-- (let* ((--cl-var-- (list (cons 'doom-cli-error (expand-file-name "cli" doom-core-dir)) (cons 'doom-core-error doom-core-dir) (cons 'doom-user-error doom-user-dir) (cons 'doom-profile-error doom-profile-dir) (cons 'doom-module-error doom-modules-dir))) (dir nil) (err nil)) (while (consp --cl-var--) (setq dir (car --cl-var--) err (pop dir)) (if (file-in-directory-p path dir) (progn (signal err (list (file-relative-name path (expand-file-name "../" dir)) e)))) (setq --cl-var-- (cdr --cl-var--))) nil))
  (cl--block-wrapper (catch '--cl-block-nil-- (let* ((--cl-var-- (list (cons 'doom-cli-error (expand-file-name "cli" doom-core-dir)) (cons 'doom-core-error doom-core-dir) (cons 'doom-user-error doom-user-dir) (cons 'doom-profile-error doom-profile-dir) (cons 'doom-module-error doom-modules-dir))) (dir nil) (err nil)) (while (consp --cl-var--) (setq dir (car --cl-var--) err (pop dir)) (if (file-in-directory-p path dir) (progn (signal err (list (file-relative-name path (expand-file-name "../" dir)) e)))) (setq --cl-var-- (cdr --cl-var--))) nil)))
  (cl-block nil (let* ((--cl-var-- (list (cons 'doom-cli-error (expand-file-name "cli" doom-core-dir)) (cons 'doom-core-error doom-core-dir) (cons 'doom-user-error doom-user-dir) (cons 'doom-profile-error doom-profile-dir) (cons 'doom-module-error doom-modules-dir))) (dir nil) (err nil)) (while (consp --cl-var--) (setq dir (car --cl-var--) err (pop dir)) (if (file-in-directory-p path dir) (progn (signal err (list (file-relative-name path (expand-file-name "../" dir)) e)))) (setq --cl-var-- (cdr --cl-var--))) nil))
  (cl-loop for (err . dir) in (list (cons 'doom-cli-error (expand-file-name "cli" doom-core-dir)) (cons 'doom-core-error doom-core-dir) (cons 'doom-user-error doom-user-dir) (cons 'doom-profile-error doom-profile-dir) (cons 'doom-module-error doom-modules-dir)) if (file-in-directory-p path dir) do (signal err (list (file-relative-name path (expand-file-name "../" dir)) e)))
  (if (not (and path (featurep 'doom))) (signal (car e) (cdr e)) (cl-loop for (err . dir) in (list (cons 'doom-cli-error (expand-file-name "cli" doom-core-dir)) (cons 'doom-core-error doom-core-dir) (cons 'doom-user-error doom-user-dir) (cons 'doom-profile-error doom-profile-dir) (cons 'doom-module-error doom-modules-dir)) if (file-in-directory-p path dir) do (signal err (list (file-relative-name path (expand-file-name "../" dir)) e))))
  (condition-case e (load path noerror 'nomessage) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (setq path (locate-file path load-path (get-load-suffixes))) (if (not (and path (featurep 'doom))) (signal (car e) (cdr e)) (cl-loop for (err . dir) in (list (cons 'doom-cli-error (expand-file-name "cli" doom-core-dir)) (cons 'doom-core-error doom-core-dir) (cons 'doom-user-error doom-user-dir) (cons 'doom-profile-error doom-profile-dir) (cons 'doom-module-error doom-modules-dir)) if (file-in-directory-p path dir) do (signal err (list (file-relative-name path (expand-file-name "../" dir)) e))))))
  doom-load("/home/mfj/.config/emacs/lisp/lib/files" nil)
  (or (featurep feature subfeature) (doom-load (if subfeature (file-name-concat doom-core-dir (string-remove-prefix "doom-" (symbol-name feature)) (symbol-name filename)) (symbol-name feature)) noerror))
  (let ((subfeature (if (symbolp filename) filename))) (or (featurep feature subfeature) (doom-load (if subfeature (file-name-concat doom-core-dir (string-remove-prefix "doom-" (symbol-name feature)) (symbol-name filename)) (symbol-name feature)) noerror)))
  doom-require(doom-lib files)
  apply(doom-require (doom-lib files))
  #f(compiled-function (&rest args2) #<bytecode -0x9ebb99bb0176c9c>)(files)
  mapc(#f(compiled-function (&rest args2) #<bytecode -0x9ebb99bb0176c9c>) (process system git plist files print autoloads profiles modules packages))
  (progn (let ((umask (default-file-modes))) (unwind-protect (progn (set-default-file-modes 448) (mapc (doom-rpartial #'make-directory 'parents) (list doom-local-dir doom-data-dir doom-cache-dir doom-state-dir))) (set-default-file-modes umask))) (doom-require 'doom-lib 'debug) (if init-file-debug (doom-debug-mode 1)) (require 'seq) (require 'map) (mapc (doom-partial #'doom-require 'doom-lib) '(process system git plist files print autoloads profiles modules packages)) (require 'doom-cli) (add-hook 'doom-cli-initialize-hook #'doom-finalize))
  (if (doom-context-push 'cli) (progn (let ((umask (default-file-modes))) (unwind-protect (progn (set-default-file-modes 448) (mapc (doom-rpartial #'make-directory 'parents) (list doom-local-dir doom-data-dir doom-cache-dir doom-state-dir))) (set-default-file-modes umask))) (doom-require 'doom-lib 'debug) (if init-file-debug (doom-debug-mode 1)) (require 'seq) (require 'map) (mapc (doom-partial #'doom-require 'doom-lib) '(process system git plist files print autoloads profiles modules packages)) (require 'doom-cli) (add-hook 'doom-cli-initialize-hook #'doom-finalize)))
  (if interactive? (if (doom-context-push 'emacs) (progn (add-hook 'doom-after-init-hook #'doom-load-packages-incrementally-h 100) (add-hook 'doom-after-init-hook #'doom-display-benchmark-h 110) (doom-run-hook-on 'doom-first-buffer-hook '(find-file-hook doom-switch-buffer-hook)) (doom-run-hook-on 'doom-first-file-hook '(find-file-hook dired-initial-position-hook)) (doom-run-hook-on 'doom-first-input-hook '(pre-command-hook)) (progn (defalias 'doom-run-first-hooks-if-files-open-h #'(lambda nil (if file-name-history (progn (doom-run-hooks 'doom-first-file-hook 'doom-first-buffer-hook))))) (let ((tail '(doom-after-init-hook))) (while tail (let ((hook (car tail))) (let ((tail (list #'doom-run-first-hooks-if-files-open-h))) (while tail (let ((func (car tail))) (add-hook hook func 100 nil) (setq tail (cdr tail))))) (setq tail (cdr tail)))))) (add-hook 'after-change-major-mode-hook #'doom-run-local-var-hooks-h 100) (add-hook 'hack-local-variables-hook #'doom-run-local-var-hooks-h) (advice-add #'command-line-1 :after #'doom-finalize) (require 'doom-start) (let ((init-file (doom-profile-init-file doom-profile))) (or (doom-load init-file t) (signal 'doom-nosync-error (list init-file)))))) (if (doom-context-push 'cli) (progn (let ((umask (default-file-modes))) (unwind-protect (progn (set-default-file-modes 448) (mapc (doom-rpartial #'make-directory 'parents) (list doom-local-dir doom-data-dir doom-cache-dir doom-state-dir))) (set-default-file-modes umask))) (doom-require 'doom-lib 'debug) (if init-file-debug (doom-debug-mode 1)) (require 'seq) (require 'map) (mapc (doom-partial #'doom-require 'doom-lib) '(process system git plist files print autoloads profiles modules packages)) (require 'doom-cli) (add-hook 'doom-cli-initialize-hook #'doom-finalize))))
  (progn (if (daemonp) (progn (message "Starting Doom Emacs in daemon mode...") (if doom-inhibit-log nil (progn (let ((tail '(doom-after-init-hook))) (while tail (let ((hook (car tail))) (let ((tail (list #'(lambda (&rest _) (if doom-inhibit-log nil (setq doom-inhibit-log (not (or noninteractive init-file-debug)))) (message "Disabling verbose mode. Have fun!"))))) (while tail (let ((func (car tail))) (add-hook hook func 106 nil) (setq tail (cdr tail))))) (setq tail (cdr tail)))))) (progn (let ((tail '(kill-emacs-hook))) (while tail (let ((hook (car tail))) (let ((tail (list #'(lambda (&rest _) (message "Killing Emacs. Sayonara!"))))) (while tail (let ((func (car tail))) (add-hook hook func 110 nil) (setq tail (cdr tail))))) (setq tail (cdr tail))))))))) (if interactive? (if (doom-context-push 'emacs) (progn (add-hook 'doom-after-init-hook #'doom-load-packages-incrementally-h 100) (add-hook 'doom-after-init-hook #'doom-display-benchmark-h 110) (doom-run-hook-on 'doom-first-buffer-hook '(find-file-hook doom-switch-buffer-hook)) (doom-run-hook-on 'doom-first-file-hook '(find-file-hook dired-initial-position-hook)) (doom-run-hook-on 'doom-first-input-hook '(pre-command-hook)) (progn (defalias 'doom-run-first-hooks-if-files-open-h #'(lambda nil (if file-name-history (progn (doom-run-hooks 'doom-first-file-hook 'doom-first-buffer-hook))))) (let ((tail '(doom-after-init-hook))) (while tail (let ((hook (car tail))) (let ((tail (list #'doom-run-first-hooks-if-files-open-h))) (while tail (let ((func (car tail))) (add-hook hook func 100 nil) (setq tail (cdr tail))))) (setq tail (cdr tail)))))) (add-hook 'after-change-major-mode-hook #'doom-run-local-var-hooks-h 100) (add-hook 'hack-local-variables-hook #'doom-run-local-var-hooks-h) (advice-add #'command-line-1 :after #'doom-finalize) (require 'doom-start) (let ((init-file (doom-profile-init-file doom-profile))) (or (doom-load init-file t) (signal 'doom-nosync-error (list init-file)))))) (if (doom-context-push 'cli) (progn (let ((umask (default-file-modes))) (unwind-protect (progn (set-default-file-modes 448) (mapc (doom-rpartial #'make-directory 'parents) (list doom-local-dir doom-data-dir doom-cache-dir doom-state-dir))) (set-default-file-modes umask))) (doom-require 'doom-lib 'debug) (if init-file-debug (doom-debug-mode 1)) (require 'seq) (require 'map) (mapc (doom-partial #'doom-require 'doom-lib) '(process system git plist files print autoloads profiles modules packages)) (require 'doom-cli) (add-hook 'doom-cli-initialize-hook #'doom-finalize)))) (let ((site-loader #'(lambda nil (if init-file-debug (progn (if interactive? nil (require 'cl nil t)) (if site-run-file nil (let* ((site-file (and t (get 'site-run-file 'initial-value)))) (if site-file (let ((inhibit-startup-screen inhibit-startup-screen)) (setq site-run-file site-file) (load site-run-file t)))))) (let ((standard-output #'(lambda (&rest _)))) (let ((message (symbol-function #'message))) (ignore message) (let* ((vnew #'(lambda (&rest _) "\n\n(fn &rest ##)" nil)) (old (symbol-function #'message))) (unwind-protect (progn (fset #'message vnew) (let ((load (symbol-function #'load))) (ignore load) (let* ((vnew #'(lambda (file &optional noerror nomessage nosuffix must-suffix) (funcall load file noerror t nosuffix must-suffix))) (old (symbol-function #'load))) (unwind-protect (progn (fset #'load vnew) (let ((write-region (symbol-function #'write-region))) (ignore write-region) (let* ((vnew #'(lambda (start end filename &optional append visit lockname mustbenew) (progn (if visit nil (setq visit 'no-message)) (funcall write-region start end filename append visit lockname mustbenew)))) (old (symbol-function #'write-region))) (unwind-protect (progn (fset #'write-region vnew) (progn (if interactive? nil (require 'cl nil t)) (if site-run-file nil (let* ((site-file (and t (get 'site-run-file 'initial-value)))) (if site-file (let ((inhibit-startup-screen inhibit-startup-screen)) (setq site-run-file site-file) (load site-run-file t))))))) (fset #'write-region old))))) (fset #'load old))))) (fset #'message old))))))))) (if interactive? (prog1 (defalias 'startup--load-user-init-file@load-site-files #'(lambda (&rest _) (funcall site-loader))) (advice-add 'startup--load-user-init-file :before #'startup--load-user-init-file@load-site-files '((depth . 100) (name . load-site-files)))) (funcall site-loader))) (doom-run-hooks 'doom-before-init-hook) (setq features (cons :system (delq :system features))) (let ((tail '(exec-path load-path process-environment))) (while tail (let ((var (car tail))) (put var 'initial-value (default-toplevel-value var)) (setq tail (cdr tail))))) t)
  (if (doom-context-push 'startup) (progn (if (daemonp) (progn (message "Starting Doom Emacs in daemon mode...") (if doom-inhibit-log nil (progn (let ((tail '(doom-after-init-hook))) (while tail (let ((hook (car tail))) (let ((tail (list #'(lambda (&rest _) (if doom-inhibit-log nil (setq doom-inhibit-log (not (or noninteractive init-file-debug)))) (message "Disabling verbose mode. Have fun!"))))) (while tail (let ((func (car tail))) (add-hook hook func 106 nil) (setq tail (cdr tail))))) (setq tail (cdr tail)))))) (progn (let ((tail '(kill-emacs-hook))) (while tail (let ((hook (car tail))) (let ((tail (list #'(lambda (&rest _) (message "Killing Emacs. Sayonara!"))))) (while tail (let ((func (car tail))) (add-hook hook func 110 nil) (setq tail (cdr tail))))) (setq tail (cdr tail))))))))) (if interactive? (if (doom-context-push 'emacs) (progn (add-hook 'doom-after-init-hook #'doom-load-packages-incrementally-h 100) (add-hook 'doom-after-init-hook #'doom-display-benchmark-h 110) (doom-run-hook-on 'doom-first-buffer-hook '(find-file-hook doom-switch-buffer-hook)) (doom-run-hook-on 'doom-first-file-hook '(find-file-hook dired-initial-position-hook)) (doom-run-hook-on 'doom-first-input-hook '(pre-command-hook)) (progn (defalias 'doom-run-first-hooks-if-files-open-h #'(lambda nil (if file-name-history (progn (doom-run-hooks 'doom-first-file-hook 'doom-first-buffer-hook))))) (let ((tail '(doom-after-init-hook))) (while tail (let ((hook (car tail))) (let ((tail (list #'doom-run-first-hooks-if-files-open-h))) (while tail (let ((func (car tail))) (add-hook hook func 100 nil) (setq tail (cdr tail))))) (setq tail (cdr tail)))))) (add-hook 'after-change-major-mode-hook #'doom-run-local-var-hooks-h 100) (add-hook 'hack-local-variables-hook #'doom-run-local-var-hooks-h) (advice-add #'command-line-1 :after #'doom-finalize) (require 'doom-start) (let ((init-file (doom-profile-init-file doom-profile))) (or (doom-load init-file t) (signal 'doom-nosync-error (list init-file)))))) (if (doom-context-push 'cli) (progn (let ((umask (default-file-modes))) (unwind-protect (progn (set-default-file-modes 448) (mapc (doom-rpartial #'make-directory 'parents) (list doom-local-dir doom-data-dir doom-cache-dir doom-state-dir))) (set-default-file-modes umask))) (doom-require 'doom-lib 'debug) (if init-file-debug (doom-debug-mode 1)) (require 'seq) (require 'map) (mapc (doom-partial #'doom-require 'doom-lib) '(process system git plist files print autoloads profiles modules packages)) (require 'doom-cli) (add-hook 'doom-cli-initialize-hook #'doom-finalize)))) (let ((site-loader #'(lambda nil (if init-file-debug (progn (if interactive? nil (require 'cl nil t)) (if site-run-file nil (let* ((site-file (and t (get 'site-run-file 'initial-value)))) (if site-file (let ((inhibit-startup-screen inhibit-startup-screen)) (setq site-run-file site-file) (load site-run-file t)))))) (let ((standard-output #'(lambda (&rest _)))) (let ((message (symbol-function #'message))) (ignore message) (let* ((vnew #'(lambda (&rest _) "\n\n(fn &rest ##)" nil)) (old (symbol-function #'message))) (unwind-protect (progn (fset #'message vnew) (let ((load (symbol-function #'load))) (ignore load) (let* ((vnew #'(lambda (file &optional noerror nomessage nosuffix must-suffix) (funcall load file noerror t nosuffix must-suffix))) (old (symbol-function #'load))) (unwind-protect (progn (fset #'load vnew) (let ((write-region (symbol-function #'write-region))) (ignore write-region) (let* ((vnew #'(lambda (start end filename &optional append visit lockname mustbenew) (progn (if visit nil (setq visit 'no-message)) (funcall write-region start end filename append visit lockname mustbenew)))) (old (symbol-function #'write-region))) (unwind-protect (progn (fset #'write-region vnew) (progn (if interactive? nil (require 'cl nil t)) (if site-run-file nil (let* ((site-file (and t (get 'site-run-file 'initial-value)))) (if site-file (let ((inhibit-startup-screen inhibit-startup-screen)) (setq site-run-file site-file) (load site-run-file t))))))) (fset #'write-region old))))) (fset #'load old))))) (fset #'message old))))))))) (if interactive? (prog1 (defalias 'startup--load-user-init-file@load-site-files #'(lambda (&rest _) (funcall site-loader))) (advice-add 'startup--load-user-init-file :before #'startup--load-user-init-file@load-site-files '((depth . 100) (name . load-site-files)))) (funcall site-loader))) (doom-run-hooks 'doom-before-init-hook) (setq features (cons :system (delq :system features))) (let ((tail '(exec-path load-path process-environment))) (while tail (let ((var (car tail))) (put var 'initial-value (default-toplevel-value var)) (setq tail (cdr tail))))) t))
  doom-initialize(nil)
  (if (let ((load-suffixes '(".elc" ".el")) (doom (expand-file-name "lisp/doom" user-emacs-directory))) (if (file-exists-p (concat doom ".el")) (load doom nil (not init-file-debug) nil 'must-suffix) (prog1 (defalias 'startup--load-user-init-file@reroute-to-profile #'(lambda (args) (list #'(lambda nil (expand-file-name "init.el" user-emacs-directory)) nil (nth 2 args)))) (advice-add 'startup--load-user-init-file :filter-args #'startup--load-user-init-file@reroute-to-profile '((name . reroute-to-profile)))) (setq user-init-file (expand-file-name "early-init" user-emacs-directory)) (setq load-prefer-newer t) (setq gc-cons-threshold (* 16 1024 1024)) nil)) (doom-initialize (not noninteractive)) (load user-init-file 'noerror (not init-file-debug) nil 'must-suffix))
  (let (file-name-handler-alist) (if noninteractive (progn (setq gc-cons-threshold 134217728) (setq gc-cons-percentage 1.0)) (setq gc-cons-threshold most-positive-fixnum)) (setq load-prefer-newer noninteractive) (let ((debug (getenv-internal "DEBUG"))) (if (stringp debug) (progn (if (string-empty-p debug) (setenv "DEBUG" nil) (progn (setq init-file-debug t) (setq debug-on-error t)))))) (let ((command-line-args (if noninteractive nil command-line-args)) (profile (or (car (cdr (member "--profile" command-line-args))) (getenv-internal "DOOMPROFILE")))) (if (null profile) (let ((init-dir (or (car (cdr (member "--init-directory" command-line-args))) (getenv-internal "EMACSDIR")))) (if (null init-dir) (if noninteractive (progn (setq user-emacs-directory (file-name-directory (file-truename load-file-name))))) (setq command-switch-alist (cons (cons "--init-directory" #'(lambda (_) (car-safe (prog1 argv (setq argv (cdr argv)))))) command-switch-alist)) (setq user-emacs-directory (expand-file-name init-dir)))) (setq command-switch-alist (cons (cons "--profile" #'(lambda (_) (car-safe (prog1 argv (setq argv (cdr argv)))))) command-switch-alist)) (setenv "DOOMPROFILE" profile) (or (load (let ((windows? (memq system-type '(ms-dos windows-nt cygwin)))) (expand-file-name (format (or (getenv-internal "DOOMPROFILELOADFILE") (file-name-concat (if windows? "doomemacs/data" "doom") "profiles.%d")) emacs-major-version) (or (if windows? (getenv-internal "LOCALAPPDATA")) (getenv-internal "XDG_DATA_HOME") "~/.local/share"))) 'noerror (not init-file-debug)) (user-error "Profiles not initialized yet; run 'doom sync' first")))) (if (let ((load-suffixes '(".elc" ".el")) (doom (expand-file-name "lisp/doom" user-emacs-directory))) (if (file-exists-p (concat doom ".el")) (load doom nil (not init-file-debug) nil 'must-suffix) (prog1 (defalias 'startup--load-user-init-file@reroute-to-profile #'(lambda (args) (list #'(lambda nil (expand-file-name "init.el" user-emacs-directory)) nil (nth 2 args)))) (advice-add 'startup--load-user-init-file :filter-args #'startup--load-user-init-file@reroute-to-profile '((name . reroute-to-profile)))) (setq user-init-file (expand-file-name "early-init" user-emacs-directory)) (setq load-prefer-newer t) (setq gc-cons-threshold (* 16 1024 1024)) nil)) (doom-initialize (not noninteractive)) (load user-init-file 'noerror (not init-file-debug) nil 'must-suffix)))
  load-with-code-conversion("/home/mfj/.config/emacs/early-init.el" "/home/mfj/.config/emacs/early-init.el" nil t)
  load("/home/mfj/.config/emacs/early-init.el" nil nomessage nosuffix)
  (and (load init-file nil 'nomessage 'nosuffix) (featurep 'doom))
  (or (and (load init-file nil 'nomessage 'nosuffix) (featurep 'doom)) (user-error "Failed to load Doom from %s" init-file))
  (let* ((bin-dir (file-name-directory (file-truename load-file-name))) (init-file (expand-file-name "../early-init.el" bin-dir))) (or (and (load init-file nil 'nomessage 'nosuffix) (featurep 'doom)) (user-error "Failed to load Doom from %s" init-file)))
  (condition-case e (let* ((bin-dir (file-name-directory (file-truename load-file-name))) (init-file (expand-file-name "../early-init.el" bin-dir))) (or (and (load init-file nil 'nomessage 'nosuffix) (featurep 'doom)) (user-error "Failed to load Doom from %s" init-file))) (user-error (message "Error: %s" (car (cdr e))) (kill-emacs 2)))
  load-with-code-conversion("/home/mfj/.config/emacs/bin/doom" "/home/mfj/.config/emacs/bin/doom" nil t)
  command-line-1(("--eval" "(setq warning-inhibit-types '((files missing-lexbind-cookie)))" "--load" "/home/mfj/.config/emacs/bin/doom" "--" "upgrade" "-p"))
  command-line()
  normal-top-level()
Unexpected error in Doom’s core: "lisp/lib/files.el", (void-function static-unless)
```

### Steps to reproduce

1. invoke `doom up`
2. Go through the upgrade process

I checked out commit c6f749e (my starting point) to be able to run `doom info`. Commit faea320 also works, which is the last commit before the refactoring of the static if, when, and unless.

### System Information

https://pastebin.com/sniEYKXD

**Comment by hlissner** [comment]
Between b2ce210 and 5f6df26 this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by markflarup** [comment]
It works, thanks 🥇

**Comment by rymndhng** [comment]
Also fixed for me on 30.1, thanks!

**Comment by ignamartinoli** [comment]
I am also stuck on this issue.

I'm on Emacs version `31.0.50`.

I deleted the `.config/emacs` directory and reinstalled Doom, but I still get the `Unexpected error in Doom’s core: "lisp/lib/files.el", (void-function static-unless)` message.

**Comment by hlissner** [comment]
@ignamartinoli Update Doom.

**Comment by ignamartinoli** [comment]
@hlissner I tried. `bin/doom` isn't functional, so I tried your approach but it failed:

```
❯ git pull
Already up to date.
❯ doom sync -u

Error: doom-core-error ("lisp/lib/files.el" (void-function static-unless))
  signal(doom-core-error ("lisp/lib/files.el" (void-function static-unless)))
  (progn (signal err (list (file-relative-name path (expand-file-name "../" dir)) e)))
...
Unexpected error in Doom’s core: "lisp/lib/files.el", (void-function static-unless)
```

What's weird is that doing a fresh install isn't working either:

```
❯ rm -r .config/emacs/
❯ git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs
Cloning into '/home/sicro/.config/emacs'...
remote: Enumerating objects: 1159, done.
remote: Counting objects: 100% (1159/1159), done.
remote: Compressing objects: 100% (1068/1068), done.
remote: Total 1159 (delta 78), reused 516 (delta 48), pack-reused 0 (from 0)
Receiving objects: 100% (1159/1159), 1.18 MiB | 2.97 MiB/s, done.
Resolving deltas: 100% (78/78), done.
❯ ~/.config/emacs/bin/doom install

Error: doom-core-error ("lisp/lib/files.el" (void-function static-unless))
  signal(doom-core-error ("lisp/lib/files.el" (void-function static-unless)))
  (progn (signal err (list (file-relative-name path (expand-file-name "../" dir)) e)))
...
```

**Comment by hlissner** [comment]
> I'm on Emacs version 31.0.50.

Then I suspect it's because you're on a commit of 31.0.50 that predates `static-{when,unless}`. I guess I'll just have to load `doom-compat` more indiscriminately. In the meantime, either downgrade to Emacs 30.1 or build a newer build of 31.

**Comment by hlissner** [comment]
With 46647da, this error should be fixed for users on 31.* on commits predating the `static-{when,unless}` macros.

**Comment by ignamartinoli** [comment]
Thanks @hlissner. It works now
